### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by sunny-starscout** [PointThink/deltachan#10]
You should make the board fade style static, just like 4chan and add a catalog, you should add a reply button for threads instead of clicking the id of their thread, and instead of using a blue banner for replying like "Replying to >>post number" You could use 4chan's old posting mode: reply system, and fix quoting, it doesn't work, one last thing though: Make it so you can click images to put them in their full size like 4chan does

Instead of this 
![Screenshot_20241028_194550_Chrome](https://github.com/user-attachments/assets/825cf07c-40ae-45c6-80af-da59562127b0)

You can do something like this
![Screenshot_20241028_194647_Chrome](https://github.com/user-attachments/assets/58115bd2-3a51-4e68-b633-5282e1be4368)

**Comment by PointThink** [comment]
Can you elaborate on what you meant with the posting mode

**Comment by PointThink** [comment]
Catalog and quoting fix pushed to branch v0.8

**Comment by sunny-starscout** [comment]
> Can you elaborate on what you meant with the posting mode

like you can use Posting mode: Reply

**Comment by PointThink** [comment]
> > Can you elaborate on what you meant with the posting mode
> 
> like you can use Posting mode: Reply

I'm still not quite sure what you mean. If you want to change the "Replying to >>id" text to "Posting mode: Reply" then no. I think the current reply banner gets the point across pretty well.

**Comment by sunny-starscout** [comment]
> > > Can you elaborate on what you meant with the posting mode
> > 
> > 
> > like you can use Posting mode: Reply
> 
> I'm still not quite sure what you mean. If you want to change the "Replying to >>id" text to "Posting mode: Reply" then no. I think the current reply banner gets the point across pretty well.

Fair enough

**Comment by PointThink** [comment]
Expandable images pushed do branch 1.0
