### ISSUE TITLE
php version

### ISSUE THREAD

**Issue by x1a7x** [PointThink/deltachan#13]
With all the strife of the breaking changes with each php ver, the latest php ver that works should be specified. Also- anything less than the very latest version of php is just silly due to all the breaking changes with new php versions. Also, if you combine the small php files into  fewer larger ones, it is easy to feed the code to chatgpt or similar in order to audit the code and instantly make changes. Of note, ive seen ChatGPT audit similar PHP  ib's and find tons of security vulns. The larger the code base is with PHP, the more vulns. Its why no one cares about php any more. ChatGPT can make a similar  board with lesser GO or RUST code and it would be way more secure. PHP is nice for its simplicity- but too much php code renders just about any php app utterly silly. To maintain the benefits of php, boards should be modular, and editable by ChatGPT or similar. 

also frameworks like Laravel or TWIG can greatly increase security- they have built in security form handling and so forth. Just ask chatgpt about it... it will explain it in great detail. It is possible to not use a framework with the big IF of IF you use the very latest php version and the code is properly made with security in mind. But be very aware that almost every php ib has serious security vulns.  GO and Rust are far superior to PHP in terms of performance and security. PHP is outdated, to be sure. YES, it is possible to make a well designed PHP ib, but great care would have to be made to actually make a secure PHP ib app- it would almost be impossible. Github is full of very NOT SECURE php ib apps. Many just try to hide bad code in lots of separate php files- and are very hackable- not secure at all.

**Comment by x1a7x** [comment]
also frameworks like Laravel or TWIG can greatly increase security- they have built in security form handling and so forth. Just ask chatgpt about it... it will explain it in great detail. It is possible to not use a framework with the big IF of IF you use the very latest version and the code is properly made with security in mind. But be very aware that almost every php ib has serious security vulns.

**Comment by PointThink** [comment]
Thanks for reminding me about security. I just discovered a fucking XSS vulnerability. It's far to easy to overlook these things for me.

**Comment by x1a7x** [comment]
look through my archived php code on git. One can fill a big page with security measures, and more vulns can be found. If you ask chatgpt to fix your security, it will find another measure practically every time you ask it to improve security. The absolute truth is php is very hard to properly secure, if not impossible. So just make php apps without sensitive data such as ip and stuff like that, it minimizes risk. Im not being an elitist or rude... but its the truth, no matter what some youtube video of the day says... php in not secure.

**Comment by x1a7x** [comment]
this is the most secure board on my side, take the code, call it your own i dont care, chat gpt made it anyway lol. But to start with security you MUST start with the latest version of php. You must. Because every php version works on better security. https://github.com/x1a7x/Adelia
