### ISSUE TITLE
ib

### ISSUE THREAD

**Issue by x1a7x** [PointThink/deltachan#17]
https://github.com/x1a7x/cat1  This is a sqlite3 ver for easy use, but i will use other db too. If you want any code or anything from it- including the full app.. go for it!! Specifically, ANY js file on vichan, (all the board functionality!!) or any vichan style sheet works on this as a drop in replacment-- how's that for awesome?

**Comment by PointThink** [comment]
I'd appreciate if you didn't flex your code on my repo

**Comment by PointThink** [comment]
> np, but since your code does not even run on my server i thought you could use a boost. Git is interesting, it seems to draw a whole bunch of ppl who want to make imageboards that do not work. So many repos like that. I am always helping ppl dev them, have been for years.

I'd prefer if you told me what the error is and provide any info about your server so I could resolve that issue.
