### ISSUE TITLE
Warning: Undefined array key 

### ISSUE THREAD

**Issue by ninjazan420** [PointThink/deltachan#19]
Hi there! Good work so far. This error happened right after my .gif upload was done. It happened [here](http://deltachan.atwebpages.com/b/post.php?id=16) on both gifs

Warning: Undefined array key "cf-turnstile-response" in /srv/disk12/3685730/www/deltachan.atwebpages.com/internal/actions/post.php on line 61
Warning: Cannot modify header information - headers already sent by (output started at /srv/disk12/3685730/www/deltachan.atwebpages.com/internal/actions/post.php:61) in /srv/disk12/3685730/www/deltachan.atwebpages.com/internal/actions/post.php on line 153

Greetings!

**Comment by PointThink** [comment]
I don't think it has anything to do with gifs. Judging by the name "cf-turnslite-response" it's trying to check the response from cloudflare's turnslite (basically a captcha) even when it's disabled. I'll take a look and try to patch it.

**Comment by PointThink** [comment]
Fixed in v1.3.1
