### ISSUE TITLE
Mejorar las instrucciones de instalación

### ISSUE THREAD

**Issue by 0x230797** [PointThink/deltachan#9]
Hola amigo, me gustaría probar el ib, pero se me dificulta la instalación ya sea en local o en un servidor, me podrías ayudar con eso?

**Comment by PointThink** [comment]
Sorry I don't speak Spanish

**Comment by sunny-starscout** [comment]
> Sorry I don't speak Spanish

They basically said that they need help installing, (Hello friend, I would like to try the ib, but I find it difficult to install either locally or on a server, could you help me with that?)

**Comment by PointThink** [comment]
What OS are you using?

**Comment by 0x230797** [comment]
Windows, también uso XAMPP con MySQL y Apache, lo que no se es que poner en la sección de "Almacenamiento seguro ", también en localhost, al momento de instalar, no me carga los css, pero en el servidor hosting si.

**Comment by PointThink** [comment]
I've never tested the software on Windows but I assume the CSS not loading has something to do with the diffrences between *nix and Windows. As for the secure storage it's the path to a file that stores the encryption keys for the database credentials. You should put it in a place where you webserver can access it and cannot be accessed externally. I'll try to make the install instructions clearer on the next release.
